version: "3.8"
services:
  deep_lt:
    runtime: nvidia
    build:
      context: .
    restart: unless-stopped
    volumes:
      - ./models:/workspace/models
      - ./notebooks:/workspace/notebooks
      - ./manifests:/workspace/manifests
      - ./logs:/workspace/logs
      - /home/martynas/ml/liepa:/data/liepa_100/
    ports:
      - 8888:8888
      - 6006:6006
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    ipc: "host"